<?php
/**
 * Created by PhpStorm.
 * User: Pasa吴
 * Date: 2019/2/11
 * Time: 19:54
 */

namespace App\Common\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class ApiBaseController extends BaseController
{
    protected $validate; // 验证器
    protected $model;
    protected $param; // 接收post和get变量
    protected $res; // 接口返回变量

    /**
     * 构造方法
     * AdminBaseController constructor.
     */
    public function __construct()
    {
        header("Content-Type: text/html; charset=UTF-8");
        // 执行父类构造方法
        parent::__construct(); // TODO: Change the autogenerated stub

        $host_name = isset($_SERVER['HTTP_ORIGIN']) ? $_SERVER['HTTP_ORIGIN'] : "*";
        header("Access-Control-Allow-Origin:{$host_name}");
        header("Access-Control-Allow-Credentials:true");
        header("Access-Control-Allow-Headers:x-token,x-uid,x-token-check,x-requested-with,content-type,Host");
        // 请求参数
        $this->param = Input::all();
    }

    /**
     *   基类验证方法
     * @param scene 验证场景
     * @param datas 验证数据
     */
    public function _checkParams($scene, $datas)
    {

        if ($this->validate && $this->validate->scene($scene)->check($datas) === false) {
            $this->jump([DATA_DISABLE, $this->validate->getError(), $this->param]);
        }

        return true;
    }


}